- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: myservers
  become: yes
  tasks:
    - name: Install latest version of Apache
      apt: 
        name: apache2 
        update_cache: yes 
        state: latest
 
    - name: Create document root for domain configured in host variable
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      when: false
 
    - name: Copy your index file
      template:
        src: "files/index-template.html"
        dest: "/var/www/html/index.html"
 
    - name: Set up virtuahHost
      template:
        src: "files/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      when: false
 
    - name: Enable site
      command: a2ensite {{ http_conf }}
      notify: restart-apache
      when: false
 
    - name: "UFW firewall allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
 
  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
