name: Artifact test Workflow

on:
  workflow_dispatch:
   inputs:
    logLevel:
      description: 'Log level'     
      required: true
      default: 'warning'
    variable1:
      description: 'mi variable custom'
      required: False
      default: 'value1test'

jobs:
  manage_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create dir to save file
        run: mkdir my_dir
        
      - name: Create file
        run: echo "hola mundo" >> my_dir/my_file.txt
        
      - name: Uplaod file to artifact
        uses: actions/upload-artifact@v3
        with:
          name: my_file_subido
          path: my_dir/my_file.txt
          
      - name: download file from artifact
        uses: actions/download-artifact@v3
        with:
          name: my_file_subido
          
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
  
  job_test_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

  download_other_job_artifact:
    runs-on: ubuntu-latest
    steps:
          
      - name: download file from artifact
        uses: actions/download-artifact@v3
        with:
          name: my_file_subido
        

