name: MS Teams Notification

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Microsoft Teams Notification Action
        uses: mateuschaves/notify-ms-teams-github-fix@1.1
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: mensaje enviado desde un workflow de github
          notification-color: 17a2b8
          timezone: Europe/Madrid
